# Generated by Django 4.2.11 on 2024-03-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_ssn', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('emp_efficiency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('no_of_holes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('job_name', models.ForeignKey(db_column='job_name', default='default_job_name', on_delete=django.db.models.deletion.CASCADE, to='webapp.job')),
            ],
            options={
                'unique_together': {('machine_name', 'job_name')},
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('max_length', models.FloatField()),
                ('cost', models.FloatField()),
                ('length_cut', models.FloatField()),
                ('no_of_brk_points', models.IntegerField()),
                ('tool_efficiency', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='tool_code',
            field=models.ForeignKey(db_column='tool_code', on_delete=django.db.models.deletion.CASCADE, to='webapp.tool'),
        ),
        migrations.CreateModel(
            name='Performs',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('shift_number', models.IntegerField()),
                ('shift_duration', models.FloatField()),
                ('achieved', models.IntegerField()),
                ('partial_shift', models.IntegerField()),
                ('target', models.IntegerField()),
                ('emp_ssn', models.ForeignKey(db_column='emp_ssn', on_delete=django.db.models.deletion.CASCADE, to='webapp.employee')),
                ('job_name', models.ForeignKey(db_column='job_name', on_delete=django.db.models.deletion.CASCADE, to='webapp.job')),
                ('machine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.machine')),
            ],
            options={
                'unique_together': {('date', 'emp_ssn', 'job_name')},
            },
        ),
    ]
