# Generated by Django 4.2.11 on 2024-03-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_ssn', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('emp_efficiency', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job_name', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('no_of_holes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=100)),
                ('tool_name', models.CharField(max_length=100)),
                ('job_id', models.ForeignKey(db_column='job_id', default='default_job_id', on_delete=django.db.models.deletion.CASCADE, to='webapp.job')),
            ],
            options={
                'unique_together': {('machine_id', 'job_id')},
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('max_length', models.FloatField()),
                ('cost', models.FloatField()),
                ('length_cut', models.FloatField()),
                ('no_of_brk_points', models.IntegerField()),
                ('tool_efficiency', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='tool_code',
            field=models.ForeignKey(db_column='tool_code', on_delete=django.db.models.deletion.CASCADE, to='webapp.tool'),
        ),
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('length_used', models.FloatField()),
                ('expected_length_remaining', models.FloatField()),
                ('replaced_by', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('change_time', models.DurationField()),
                ('no_of_min_shift', models.IntegerField()),
                ('machine_id', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.CASCADE, to='webapp.machine')),
                ('tool_code', models.ForeignKey(db_column='tool_code', on_delete=django.db.models.deletion.CASCADE, to='webapp.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Performs',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('shift_number', models.IntegerField()),
                ('shift_duration', models.FloatField()),
                ('achieved', models.IntegerField()),
                ('partial_shift', models.IntegerField()),
                ('target', models.IntegerField()),
                ('emp_ssn', models.ForeignKey(db_column='emp_ssn', on_delete=django.db.models.deletion.CASCADE, to='webapp.employee')),
                ('job_name', models.ForeignKey(db_column='job_name', on_delete=django.db.models.deletion.CASCADE, to='webapp.job')),
                ('machine_name', models.ForeignKey(db_column='machine_name', on_delete=django.db.models.deletion.CASCADE, to='webapp.machine')),
            ],
            options={
                'unique_together': {('date', 'emp_ssn', 'job_name')},
            },
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('job_id', 'tool_code'), name='unique_job_tool_combination'),
        ),
    ]
